[package]
name = "cncli"
version = "6.8.0"
authors = ["Andrew Westberg <andrewwestberg@gmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bech32 = "0.12.0"
bincode = "2"
pallas-crypto = "1.2"
pallas-math = "1.2"
pallas-network = "1.2"
pallas-traverse = "1.2"
vrf_dalek = { git = "https://github.com/txpipe/vrf", rev = "044b45a1a919ba9d9c2471fc5c4d441f13086676" }
chrono = "0.4.45"
chrono-tz = "0.10"
hex = "0.4"
minicbor = { version = "0.26.5", features = ["std", "half", "derive"] }
redb = "2.6.3"
regex = "1.13.1"
reqwest = { version = "0.12.28", default-features = false, features = ["blocking", "rustls-tls-webpki-roots", "rustls-tls", "json", "gzip", "deflate"] }
rusqlite = { version = "0.40.2", features = ["bundled", "fallible_uint"] }
serde = { version = "1.0.229", features = ["derive"] }
serde-aux = "4.5"
serde_cbor = "0.11"
serde_json = "1.0.151"
structopt = "0.3"
rand = "0.10.2"
rayon = "1.12.0"
itertools = "0.15.0"
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "net", "io-util", "time", "sync", "macros"] }
thiserror = "2.0.20"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
uuid = { version = "1.26.1", features = ["v7"] }

[build-dependencies]
built = { version = "0.8.1", features = ["git2"] }
